spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logefi?serverTimezone=UTC
    username: root
    password: Ab1142243318*
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-wait-millis: 150
      max-total: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.main.qa_logefi.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
